<?php
// kartik new created for diu
/**
 *  ProjectDiu class file
 */

/**
 * ProjectDiu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin
 */
class ProjectDiu extends PluginProjectDiu {

	const ACTIVE_PROJECT_DIU = 0;
	const DELETED_PROJECT_DIU = 1;
	
	
}
