 
<?php

// kartik new created for diu

/**
 * PluginProjectDiu class file
 */

/**
 * PluginProjectDiu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin\plugin
 */
abstract class PluginProjectDiu extends BaseProjectDiu {

	const ACTIVE_PROJECT = 0;
	const DELETED_PROJECT = 1;
}