<?php
//kartik
/**
 * BaseProjectDiu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $diuId
 * @property integer $projectId 
 * @property integer $is_deleted
 * @property string  $name
 * @property Project $Project 
 * 
 * @method integer             getDiuId()         Returns the current record's "diuId" value
 * @method integer             getProjectId()     Returns the current record's "projectId" value 
 * @method integer             getIsDeleted()     Returns the current record's "is_deleted" value
 * @method string              getName()          Returns the current record's "name" value
 * @method Project             getProject()       Returns the current record's "Project" value 
 * @method ProjectDiu          setDiuId()         Sets the current record's "diuId" value
 * @method ProjectDiu          setProjectId()     Sets the current record's "projectId" value 
 * @method ProjectDiu          setIsDeleted()     Sets the current record's "is_deleted" value
 * @method ProjectDiu          setName()          Sets the current record's "name" value
 * @method ProjectDiu          setProject()       Sets the current record's "Project" value 
 * 
 * @package    orangehrm
 * @subpackage model\admin\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectDiu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_diu');
        $this->hasColumn('diu_id as diuId', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('project_id as projectId', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             )); 
        $this->hasColumn('is_deleted', 'integer', 1, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 1,
             ));
        $this->hasColumn('name', 'string', 110, array(
             'type' => 'string',
             'length' => 110,
             ));

    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'project_id'));
    }
} 
