<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/03/22 08:24:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=hrm_fcs',
  'username' => 'fdbuser',
  'password' => 'FiV35pas5',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
